service: default
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css/(.+)
  static_files:  dist/css/\1
  upload: dist/css/(.*)

- url: /js/(.+)
  static_files:  dist/js/\1
  upload: dist/js/(.*)

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^node_modules/(.*/)?
- ^src/(.*/)?
