service: default
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  static_files: dist/\1
  upload: dist/(.*)

libraries:
- name: webapp2
  version: "2.5.2"

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^README\..*
- \.gitignore
- ^\.git/.*
- ^node_modules/(.*/)?
- ^src/(.*/)?
